name: 'ApiGen Docs'
description: 'Github Action To Generate Code Docs Website For PHP Using ApiGen'
author: 'varunsridharan'
branding:
  icon: 'hard-drive'
  color: 'green'
inputs:
  push_to_branch:
    description: 'Which Branch/Folder To Push'
    default: 'gh-pages'
  before_cmd:
    description: 'Custom Command To Run Before Generating Docs'
    default: ''
  after_cmd:
    description: 'Custom Command To Run After Generating Docs'
    default: ''
  auto_push:
    description: 'IF this can auto push to the repo'
    default: 'yes'
  output_folder:
    description: 'Custom Output Folder if auto_push is disabled'
    default: ''
  source_folder:
    description: 'Custom Source Folder'
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.push_to_branch }}
    - ${{ inputs.before_cmd }}
    - ${{ inputs.after_cmd }}
    - ${{ inputs.auto_push }}
    - ${{ inputs.output_folder }}